{"nuts_across_flats":{"type":"float"},"radial_holes_r_vector":{"type":"float"},"finger_diameter":{"end":40.0,"step":1,"type":"range","start":2.2},"flange_height":{"type":"float"},"axle_thickness":{"end":10.0,"step":1,"type":"range","start":1.0},"build_plate_manual_x":{"end":400.0,"step":1,"type":"range","start":100.0},"screw_diameter":{"type":"float"},"nut_height":{"type":"float"},"layer_thickness":{"end":0.2,"step":1,"type":"range","start":0.05},"flange_holes_number":{"type":"float"},"axle_diameter":{"end":10.0,"step":1,"type":"range","start":1.0},"build_plate_manual_y":{"end":400.0,"step":1,"type":"range","start":100.0},"axle_lenght":{"type":"float"},"shell_thickness":{"end":5.0,"step":1,"type":"range","start":0.2},"hub_diameter":{"type":"float"},"finger_height":{"type":"float"},"build_plate_selector":{"values":["0","1","2","3"],"type":"enum"},"nuts_external_diameter":{"type":"float"}}